# Generated by Django 5.1.7 on 2025-04-01 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('clothing_type', models.CharField(max_length=50)),
                ('occasion', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('fabric', models.CharField(max_length=50)),
                ('color_palette', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='wardrobe_items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
