# Generated by Django 5.1.7 on 2025-04-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_collectionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
