# Generated by Django 5.1.7 on 2025-04-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_useraccount_height_useraccount_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='fit_category',
            field=models.CharField(blank=True, choices=[('Slim Fit', 'Slim Fit'), ('Regular', 'Regular'), ('Athletic', 'Athletic'), ('Plus Size', 'Plus Size')], max_length=20, null=True),
        ),
    ]
