# Generated by Django 5.1.7 on 2025-04-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_collectionitem_fit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='fit_category',
        ),
    ]
